#!/usr/bin/bash
# Convert Folder including subdirectories to H265
# DELETES files after conversion

HANDBRAKEEXPORT="/path/to/.json.file

if ! type pv mediainfo HandBrakeCLI  &> /dev/null
then
    echo "*** Make sure HandbrakeCLI,ffmpeg, pv, and mediainfo are installed! ***"
    exit
fi

find . -type f \( -name "*.avi" -o -name "*.mp4" -o -name "*.mkv" ! -name "*265*" \) -exec sh -c '
  for f do
                OLD=$(du -h "$f"| cut -f 1)
                
                echo "Converting "$f""
                mediainfo "$f"|grep HEVC || pv -c -pte "$f" | HandBrakeCLI --preset-import-file "$HANDBRAKEEXPORT" -i "$f" \ 
                -o "{f%.*}-H265.mkv && rm -rf "$f"        
                
                NEW=$(du -h "${f%.*}"-H265.mkv | cut -f 1)
                echo "Original Size = "$OLD"" 
                echo "New Size = "$NEW"" 
done  ' sh {} +
